### PR TITLE
Fix pop and numbered examples

### PR DESCRIPTION
**Pull request by pepe**
Hello. Thanks for the library. 

I went through the examples and changed the `import` to `use` to work for me.

I also added self in `:pop` call. 

The code is formatted with `spork/fmt` let me know. If it is a problem, I will remove it.

### CODE REVIEW

**Comment by AlecTroemel** [comment]
Hey thanks for the PR!  I'm all for auto formatted code, just haven't set up `spork/fmt` on my machine yet :man_facepalming: .  These changes LGTM

**Comment by pepe** [comment]
Thanks! Also, would you consider moving the code one level up and remove the `src/`? It is the preferred way in Janet.

**Comment by AlecTroemel** [comment]
@pepe something like this?
```
.git
README.md
project.janet
junk-drawer.janet
junk-drawer/
  - esc.janet
  - ect
```

**Comment by pepe** [comment]
Yep. Also, I found some other issues that I would like to discuss with you. I will make PR with them just for the discussion.

**Comment by pepe** [comment]
Oh. I found that you put in quite an effort, as I was sleeping. Thank you very much. I will try to digest the changes and come back.

**Comment by AlecTroemel** [comment]
I doubt I fixed any of your issues, I think I just changed up the file structure (and added a new very simple FSM)

**Comment by pepe** [comment]
So do you think I can advance my issues in PR? No problem if you are not interested. These are mostly about the API design and definitely not big ones.

And mind you, my last experience with game development is more than 30 years old. But I found this lib well thought out and want to use it.

**Comment by AlecTroemel** [comment]
thanks :smile: 

I have no problem with API changes at this point, since I expect there to be better ways of doing things then what I've written so far. I'm fine with PR's or Issues for discussing/proposing changes, whatever works best for your workflow.

**Pull request merged**
